---
- hosts: localhost
  gather_facts: False
  tasks:
  - digital_ocean: >
      state=deleted
      name={{ item | regex_replace('\.', '-') }}
      unique_name=true
      command=droplet
      wait_timeout=60
    with_items: groups['all']
